# File location: action.yml
name: 'Greeting Action'
description: 'This action greets users when they open issues or pull requests.'
author: 'Your Name'

inputs:
  github-token:
    description: 'GitHub token for authentication.'
    required: true
  issue-message:
    description: 'The message to post when an issue is opened.'
    required: true
  pr-message:
    description: 'The message to post when a pull request is opened.'
    required: true
  footer:
    description: 'Optional footer message to include in the greeting.'
    required: false

runs:
  using: 'node16'
  main: 'index.js'  # This points to the script that executes the action logic

branding:
  icon: 'wave'
  color: 'blue'
